//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginSreen.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MusteriBilgileri
    {
        public short musteriID { get; set; }
        [Required(ErrorMessage = "Kullanýcý Adý boþ býrakýlamaz!")]
        [StringLength(50,ErrorMessage = "Kullanýcý Adýnýz en fazla 50 karakter olmalýdýr.")]
        public string KullaniciAdi { get; set; }
        [Required(ErrorMessage ="Þifre Alaný boþ býrakýlamaz!")]
        public string Sifre { get; set; }
    }
}
